image: alpine:latest

# ---------------------------------------
# Global
# ---------------------------------------

stages:
  - build
  - test
  - deploy

variables:
  CI: true

# ----------------------------------------
# Prescript
# ----------------------------------------

# ----------------------------------------
# Build
# ----------------------------------------

build:
  stage: build
  image: davidhrbac/docker-shellcheck
  script:
    - sh build/lint.sh
  only:
    - web
    - master

# ----------------------------------------
# Tests
# ----------------------------------------

test-entrypoint:
  stage: test
  image: jrbeverly/bats:baseimage
  script:
    - sh .docker/provision.sh
    - sh tests/integration/run.sh
  dependencies:
    - build
  only:
    - web
    - master

test-unit:
  stage: test
  image: jrbeverly/bats:baseimage
  script:
    - sh .docker/provision.sh
    - sh tests/unit/run.sh
  dependencies:
    - test-entrypoint
  only:
    - web
    - master

test-integration:
  stage: test
  image: jrbeverly/bats:baseimage
  script:
    - sh .docker/provision.sh
    - sh tests/integration/run.sh
  dependencies:
    - test-unit
  only:
    - web
    - master

# ----------------------------------------
# Deploy
# ----------------------------------------

deploy:
  stage: deploy
  script:
    - echo "Packaging up hooks"
  artifacts:
    expire_in: 4 weeks
    paths:
      - src/*
  only:
    - web
    - master