image: alpine:latest

# ---------------------------------------
# Global
# ---------------------------------------

stages:
  - build
  - test_entry
  - test_unit
  - test_integration
  - deploy

variables:
  CI: "true"

# ----------------------------------------
# Prescript
# ----------------------------------------

# ----------------------------------------
# Build
# ----------------------------------------

build:
  stage: build
  image: davidhrbac/docker-shellcheck
  script:
    - sh build/lint.sh
  only:
    - web
    - master

# ----------------------------------------
# Tests
# ----------------------------------------

test-entrypoint:
  stage: test_entry
  image: jrbeverly/bats:baseimage
  script:
    - sh .docker/provision.sh
    - sh tests/integration/run.sh
  dependencies:
    - build
  only:
    - web
    - master

test-unit:
  stage: test_unit
  image: jrbeverly/bats:baseimage
  script:
    - sh .docker/provision.sh
    - sh tests/unit/run.sh
  dependencies:
    - build
  only:
    - web
    - master

test-integration:
  stage: test_integration
  image: jrbeverly/bats:baseimage
  script:
    - sh .docker/provision.sh
    - sh tests/integration/run.sh
  dependencies:
    - build
  only:
    - web
    - master

# ----------------------------------------
# Deploy
# ----------------------------------------

deploy:
  stage: deploy
  script:
    - apk add -U zip
    - sh build/package.sh
  artifacts:
    expire_in: 4 weeks
    paths:
      - out/githooks*.zip
  only:
    - web
    - master